

server:
  port: 5007


spring:
  application:
    name: notification-service




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/salon
    username: yq9eAkzxxvnYuz5.root
    password: ER5KAuU7ycb51i90

  rabbitmq:
    host: armadillo.rmq.cloudamqp.com
    port: 5672
    username: avhqyyix
    password: ghDX0t0EkLkCdj0-wcDgtm2Honpt9sDk
    virtual-host: avhqyyix


eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-4.onrender.com/eureka/